### ISSUE TITLE
Pipeline Tekton getting an error to deploy with resource quotas

### ISSUE THREAD

**Issue by eniomachado** [tektoncd/website#265] opened 2021-04-13 22:21 UTC
I'm doing an simple test with the tekton, I'm using in openshift but i cant deploy in any namespace that has resource quotas.

apiVersion: v1
items:
- apiVersion: tekton.dev/v1beta1
  kind: TaskRun
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{},"name":"socketclient","namespace":"oxt-dev"},"spec":{"steps":[{"args":["echo test git app\ncurl https://git.app.com.br -I\necho -----------------------------------\n\necho test github\ncurl https://github.com/tektoncd -I\necho -----------------------------------"],"command":["/bin/bash","-c"],"image":"quay.io/openshift/origin-cli:latest","name":"apply","workingDir":"/workspace/source"}],"workspaces":[{"name":"source"}]}}
      pipeline.tekton.dev/release: devel
    creationTimestamp: "2021-04-13T21:43:52Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: tekton-pipelines
      tekton.dev/pipeline: socketclient-pipeline
      tekton.dev/pipelineRun: socketclient-pipeline-run-xv4zf
      tekton.dev/pipelineTask: socketclient
      tekton.dev/task: socketclient
    managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:pipeline.tekton.dev/release: {}
          f:labels:
            .: {}
            f:tekton.dev/pipeline: {}
            f:tekton.dev/pipelineRun: {}
            f:tekton.dev/pipelineTask: {}
            f:tekton.dev/task: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"648d7aef-f3e0-4c60-a1af-bb4fd392e17a"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          .: {}
          f:resources: {}
          f:serviceAccountName: {}
          f:taskRef:
            .: {}
            f:kind: {}
            f:name: {}
          f:timeout: {}
          f:workspaces: {}
        f:status:
          .: {}
          f:conditions: {}
          f:podName: {}
          f:startTime: {}
          f:taskSpec:
            .: {}
            f:steps: {}
            f:workspaces: {}
      manager: openshift-pipelines-controller
      operation: Update
      time: "2021-04-13T21:43:53Z"
    name: socketclient-pipeline-run-xv4zf-socketclient-t5gg7
    namespace: oxt-dev
    ownerReferences:
    - apiVersion: tekton.dev/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: PipelineRun
      name: socketclient-pipeline-run-xv4zf
      uid: 648d7aef-f3e0-4c60-a1af-bb4fd392e17a
    resourceVersion: "214945906"
    selfLink: /apis/tekton.dev/v1beta1/namespaces/oxt-dev/taskruns/socketclient-pipeline-run-xv4zf-socketclient-t5gg7
    uid: e237baf7-9926-4ef6-8382-434b1882fc7f
  spec:
    resources: {}
    serviceAccountName: pipeline
    taskRef:
      kind: Task
      name: socketclient
    timeout: 1h0m0s
    workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: source-pvc
  status:
    conditions:
    - lastTransitionTime: "2021-04-13T21:43:53Z"
      message: 'failed to create task run pod "socketclient-pipeline-run-xv4zf-socketclient-t5gg7":
        pods "socketclient-pipeline-run-xv4zf-socketclient-t5gg7-pod-nkt6g" is forbidden:
        failed quota: resource-quota-oxt: must specify limits.cpu,limits.memory,requests.cpu,requests.memory.
        Maybe missing or invalid Task oxt-dev/socketclient'
      reason: CouldntGetTask
      status: "False"
      type: Succeeded
    podName: ""
    startTime: "2021-04-13T21:43:53Z"
    taskSpec:
      steps:
      - args:
        - |-
          echo test git app
          curl https://git.app.com.br -I
          echo -----------------------------------

          echo test github
          curl https://github.com/tektoncd -I
          echo -----------------------------------
        command:
        - /bin/bash
        - -c
        image: quay.io/openshift/origin-cli:latest
        name: apply
        resources: {}
        workingDir: /workspace/source
      workspaces:
      - name: source

**Comment by eniomachado** [comment] 2021-04-13 22:24
#task script
 $ cat socketclient-task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: socketclient
spec:
  workspaces:
  - name: source
  # params:
  #   - name: manifest_dir
  #     description: The directory in source that contains yaml manifests
  #     type: string
  #     default: "k8s"
  steps:
    - name: apply
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo test app
          curl https://xxxxxxxxxxxx -I
          echo -----------------------------------

          echo test github
          curl https://github.com/tektoncd -I
          echo -----------------------------------

**Comment by eniomachado** [comment] 2021-04-13 22:27
#pipeline

$ cat pipeline.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: socketclient-pipeline
spec:
  workspaces:
  - name: shared-workspace
  # params:
  # - name: deployment-name
  #   type: string
  #   description: name of the deployment to be patched
  # - name: git-url
  #   type: string
  #   description: url of the git repo for the code of deployment
  # - name: git-revision
  #   type: string
  #   description: revision to be used from repo of the code for deployment
  #   default: "release-tech-preview-2"
  # - name: IMAGE
  #   type: string
  #   description: image to be build from the code
  tasks:
  - name: socketclient
    taskRef:
      name: socketclient
    workspaces:
    - name: source
      workspace: shared-workspace

**Comment by AlanGreene** [comment] 2021-04-14 00:10
This issue would probably be better suited in the tektoncd/pipeline repository, it's not related to the website / docs content.

Looking at the error message it appears you haven't set any resource limits or requests on your steps:
> failed quota: resource-quota-oxt: must specify limits.cpu,limits.memory,requests.cpu,requests.memory.

See the [docs for defining steps](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#defining-steps) for an example of setting these fields. You can also [specify a step template](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#specifying-a-step-template) to avoid having to set these individually on each step.

**Comment by eniomachado** [comment] 2021-04-14 13:06
@AlanGreene  thank you.

**Comment by AlanGreene** [comment] 2021-04-23 11:06
Closing as a duplicate of https://github.com/tektoncd/pipeline/issues/3879

**Closed by AlanGreene** 2021-04-23 11:06 UTC
Labels: triage/duplicate
