### ISSUE TITLE
remove unnecessary file

### ISSUE THREAD

**Issue by Arhell** [tektoncd/website#478] opened 2022-11-27 00:31 UTC
### Feature request

remove unnecessary file
https://github.com/tektoncd/website/blob/main/.hugo_build.lock
https://github.com/google/docsy/blob/main/.gitignore#L5

/assign

**Comment by geriom** [comment] 2022-11-30 17:01
Closing this. Reason: Intended behavior

**Closed by geriom** 2022-11-30 17:01 UTC
Labels: kind/feature
