### ISSUE TITLE
Manual for CLI usage link takes back to the same page in github

### ISSUE THREAD

**Issue by moficodes** [tektoncd/website#202] opened 2020-11-06 19:23 UTC
# Expected Behavior
https://tekton.dev/docs/cli has a link under _What's Next_ That is supposed to give a manual for using the cli. It should take to a location with a manual or more instruction on the cli.
# Actual Behavior
It just opens the same page source code in github. Has no extra information. 
# Steps to Reproduce the Problem

1. Browse to https://tekton.dev/docs/cli
2. Scroll to the bottom
3. Click the link `A manual for using Tekton CLI is available on GitHub.`

# Additional Info

We should remove this link and add more instruction on the CLI in this page
Or
Keep the link and add manual for the cli on a different page with the correct link.

**Comment by afrittoli** [comment] 2020-11-09 15:16
Good catch, thank you!
The issue is not on the website side though, the link is the same that is provided in the CLI repo at the bottom of the page: https://github.com/tektoncd/cli/tree/master/docs 
We should fix the issue there.

**Comment by moficodes** [comment] 2020-11-09 19:15
Should we open an Issue under cli then?

**Comment by afrittoli** [comment] 2020-11-11 17:51
> Should we open an Issue under cli then?

Yes please. Could you then link the two issues and close this one?

**Closed** 2021-05-07 17:40 UTC
Labels: lifecycle/rotten
