### ISSUE TITLE
[DOC] [FIX] Install Tekton Pipelines

### ISSUE THREAD

**Issue by eirisdg** [tektoncd/website#519] opened 2023-02-23 14:47 UTC
Tekton pipelines install page is not rendering properly.

![image](https://user-images.githubusercontent.com/5367659/220940437-3c709bad-b130-47c8-a986-7f5da4b9cb39.png)

And the link for additional configuration doesn't work.

![image](https://user-images.githubusercontent.com/5367659/220941225-410eb7f3-559a-4b8c-b672-df04c4352f06.png)

**Comment by AlanGreene** [comment] 2023-02-23 17:10
Thanks for reporting this @eirisdg 

@geriom fyi, looks like this is related to https://github.com/tektoncd/pipeline/pull/5806. The tabs aren't being rendered correctly on the website.

**Comment by geriom** [comment] 2023-02-23 21:03
@eirisdg thank you for the report.

> Tekton pipelines install page is not rendering properly.
> 
> ![image](https://user-images.githubusercontent.com/5367659/220940437-3c709bad-b130-47c8-a986-7f5da4b9cb39.png)

The problem is a delimiter, to be fixed in #516 

> And the link for additional configuration doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/5367659/220941225-410eb7f3-559a-4b8c-b672-df04c4352f06.png)

That was fixed in [this PR](https://github.com/tektoncd/pipeline/pull/6172), but wont' be reflected on the website until the next Pipelines release.

You can see everything working as expected in [this preview](https://deploy-preview-516--tekton.netlify.app/vault/pipelines-main/install/)

**Closed** 2023-03-28 16:44 UTC
