### ISSUE TITLE
"The Tekton APIs" link in https://tekton.dev/docs/overview/ links to k8s CRD page

### ISSUE THREAD

**Issue by naphatkrit** [tektoncd/website#363] opened 2022-03-28 13:37 UTC
Today, "The Tekton APIs" link just links out to the [k8s CRD page](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/). Was this supposed to link somewhere else? Are the APIs just referring to the [go APIs](https://pkg.go.dev/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1) for creating tekton CRDs as golang objects? Or are there other programmatic APIs somewhere else?

**Comment by AlanGreene** [comment] 2022-04-26 17:48
Thanks for the issue @naphatkrit and apologies for the delay responding.

We discussed this on the Docs WG today when reviewing potential issues for new contributors.

The APIs in this case are referring to the Kubernetes CRDs provided by the Tekton Pipelines project. We have another issue to make the API reference for these available on the website: https://github.com/tektoncd/website/issues/117, and there has been some recent progress on generating the required content: https://github.com/tektoncd/pipeline/issues/1250

Once that's available it would probably make sense to point to it instead of the Kubernetes docs.

A link to the go APIs would also be useful although I think that's probably better suited to some more advanced docs rather than the overview.

**Comment by naphatkrit** [comment] 2022-04-27 06:14
Great, thank you!

**Comment by lbernick** [comment] 2022-08-16 15:34
Tekton generated API references is now available for Pipelines [here](https://github.com/tektoncd/pipeline/blob/main/docs/pipeline-api.md)

**Comment by lbernick** [comment] 2022-08-16 15:35
This also looks like a duplicate of #117?

**Comment by AlanGreene** [comment] 2022-08-16 15:43
Related but not a duplicate IMO. #117 covers publishing the content of the API references on the website. The content is available for Pipelines now at the location you referenced above.

This issue is specifically related to the link in the overview doc which currently points to Kubernetes docs. Pointing to these new Pipeline API reference docs would definitely be useful but doesn't cover the Triggers portion yet. That paragraph could do with being updated to clarify that the APIs being discussed are the set of CRDs defined by Tekton. It's mentioned briefly under the 'What are the components of Tekton?' section on that page but could probably benefit from some elaboration.

**Closed** 2022-10-15 16:40 UTC
Labels: lifecycle/rotten
